# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/abbrev/all/abbrev.rbi
#
# abbrev-0.1.2

module Abbrev
  def abbrev(words, pattern = nil); end
  def self.abbrev(words, pattern = nil); end
end
class Array
  def abbrev(pattern = nil); end
end
